# Generated by Django 4.1.2 on 2022-10-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_fotosuno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotouno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Fotosuno',
            new_name='Carpeta_uno',
        ),
    ]
