# Generated by Django 4.1.2 on 2022-10-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_fotouno_rename_fotosuno_carpeta_uno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotosdos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagenes/')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('picture', models.ImageField(upload_to='imagenes/')),
            ],
        ),
    ]
