# Generated by Django 4.1.2 on 2022-10-30 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_rename_carpeta_uno_convenciones_delete_fotosdos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotouno',
            new_name='Diseños_varios',
        ),
        migrations.RenameModel(
            old_name='Estilouno',
            new_name='Extra',
        ),
    ]
