# Generated by Django 4.1.2 on 2022-10-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_rename_fotouno_diseños_varios_rename_estilouno_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('picture', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Tinturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.RenameField(
            model_name='convenciones',
            old_name='foto',
            new_name='imagenes',
        ),
        migrations.RenameField(
            model_name='diseños_varios',
            old_name='foto',
            new_name='fotografia',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='comentario',
        ),
        migrations.AddField(
            model_name='entrada',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/'),
        ),
    ]
