# Generated by Django 4.1.2 on 2022-10-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0011_estudio_tinturas_rename_foto_convenciones_imagenes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudio',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.AlterField(
            model_name='entrada',
            name='foto',
            field=models.ImageField(default=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='tinturas',
            name='nombre',
            field=models.TextField(),
        ),
    ]
