# Generated by Django 4.1.2 on 2022-10-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_delete_estudio_delete_extra_alter_entrada_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='foto',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
