# Generated by Django 4.1.2 on 2022-11-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_estudio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('informacion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Tatuadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='imagenes/')),
                ('informacion', models.TextField(max_length=300)),
            ],
        ),
    ]
